/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controladores.ControladorVistaUsuario;
import paneles.PanelUsuarioCompras;
import paneles.PanelUsuarioVender;
import paneles.PanelUsuarioVendido;
import paneles.PanelUsuarioInfo;
import paneles.PanelUsuarioNoDisponibles;
import paneles.PanelUsuarioEnVenta;
import paneles.PanelUsuarioComprar;
import javax.swing.JPanel;
import modelo.Usuario;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import paneles.PanelUsuarioDineroGastado;
import paneles.PanelUsuarioRegistroPublicaciones;

/**
 *
 * @author Pixels
 */
public class vistaUsuario extends javax.swing.JFrame {
    ControladorVistaUsuario controlador;
    Usuario usuario;

    /**
     * Creates new form vistaUsuarioPrincipal
     * @param usuario
     */
    public vistaUsuario(Usuario usuario) {
        initComponents();
        btnAccederAdmin.setVisible(false);
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        controlador = new ControladorVistaUsuario();
        mostrarBtnAdmin();
        PanelUsuarioComprar panel = new PanelUsuarioComprar(usuario);
        mostrarPanel(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnComprar = new javax.swing.JMenu();
        btnVentas = new javax.swing.JMenu();
        btnVender = new javax.swing.JMenuItem();
        btnEnVenta = new javax.swing.JMenuItem();
        btnVendido = new javax.swing.JMenuItem();
        btnNoDisponibles = new javax.swing.JMenuItem();
        btnRegistroPublicaciones = new javax.swing.JMenuItem();
        btnMisCompras = new javax.swing.JMenu();
        btnProductosComprados = new javax.swing.JMenuItem();
        btnDineroGastado = new javax.swing.JMenuItem();
        btnCuenta = new javax.swing.JMenu();
        btnGestionarCuenta = new javax.swing.JMenuItem();
        btnAccederAdmin = new javax.swing.JMenuItem();
        btnLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        btnComprar.setText("Comprar");
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnComprar);

        btnVentas.setText("Mis ventas");

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        btnVentas.add(btnVender);

        btnEnVenta.setText("En venta");
        btnEnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnVentaActionPerformed(evt);
            }
        });
        btnVentas.add(btnEnVenta);

        btnVendido.setText("Vendido");
        btnVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendidoActionPerformed(evt);
            }
        });
        btnVentas.add(btnVendido);

        btnNoDisponibles.setText("No disponibles");
        btnNoDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoDisponiblesActionPerformed(evt);
            }
        });
        btnVentas.add(btnNoDisponibles);

        btnRegistroPublicaciones.setText("Registro Publicaciones");
        btnRegistroPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPublicacionesActionPerformed(evt);
            }
        });
        btnVentas.add(btnRegistroPublicaciones);

        jMenuBar1.add(btnVentas);

        btnMisCompras.setText("Mis Compras");

        btnProductosComprados.setText("Productos");
        btnProductosComprados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosCompradosActionPerformed(evt);
            }
        });
        btnMisCompras.add(btnProductosComprados);

        btnDineroGastado.setText("Dinero gastado");
        btnDineroGastado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDineroGastadoActionPerformed(evt);
            }
        });
        btnMisCompras.add(btnDineroGastado);

        jMenuBar1.add(btnMisCompras);

        btnCuenta.setText("Cuenta");

        btnGestionarCuenta.setText("Gestionar Cuenta");
        btnGestionarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCuentaActionPerformed(evt);
            }
        });
        btnCuenta.add(btnGestionarCuenta);

        btnAccederAdmin.setText("Acceder como Administrador");
        btnAccederAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederAdminActionPerformed(evt);
            }
        });
        btnCuenta.add(btnAccederAdmin);

        btnLogOut.setText("Cerrar sesión");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        btnCuenta.add(btnLogOut);

        jMenuBar1.add(btnCuenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCuentaActionPerformed
        // TODO add your handling code here:
        PanelUsuarioInfo panel = new PanelUsuarioInfo(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnGestionarCuentaActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new vistaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseClicked
        // TODO add your handling code here:
        PanelUsuarioComprar panel = new PanelUsuarioComprar(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnComprarMouseClicked

    private void btnEnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnVentaActionPerformed
        // TODO add your handling code here:
        PanelUsuarioEnVenta panel = new PanelUsuarioEnVenta(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnEnVentaActionPerformed

    private void btnVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendidoActionPerformed
        // TODO add your handling code here:
        PanelUsuarioVendido panel = new PanelUsuarioVendido(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnVendidoActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        PanelUsuarioVender panel = new PanelUsuarioVender(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnNoDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoDisponiblesActionPerformed
        // TODO add your handling code here:
        PanelUsuarioNoDisponibles panel = new PanelUsuarioNoDisponibles(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnNoDisponiblesActionPerformed

    private void btnProductosCompradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosCompradosActionPerformed
        // TODO add your handling code here:
        PanelUsuarioCompras panel = new PanelUsuarioCompras(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnProductosCompradosActionPerformed

    private void btnRegistroPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPublicacionesActionPerformed
        // TODO add your handling code here:
        PanelUsuarioRegistroPublicaciones panel = new PanelUsuarioRegistroPublicaciones(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnRegistroPublicacionesActionPerformed

    private void btnAccederAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederAdminActionPerformed
        // TODO add your handling code here:
        new vistaAdministrador(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccederAdminActionPerformed

    private void btnDineroGastadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDineroGastadoActionPerformed
        // TODO add your handling code here:
        PanelUsuarioDineroGastado panel = new PanelUsuarioDineroGastado(usuario);
        mostrarPanel(panel);
    }//GEN-LAST:event_btnDineroGastadoActionPerformed

    private void mostrarPanel(JPanel p){
        p.setSize(700,310);
        
        panelContent.removeAll();
        panelContent.add(p, new AbsoluteConstraints(0,0,-1,-1));
        panelContent.revalidate();
        panelContent.repaint();
    }
    private void mostrarBtnAdmin(){
        boolean respuesta = controlador.validarAdmin(usuario.getUser());
        if(respuesta){
            btnAccederAdmin.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaUsuario(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAccederAdmin;
    private javax.swing.JMenu btnComprar;
    private javax.swing.JMenu btnCuenta;
    private javax.swing.JMenuItem btnDineroGastado;
    private javax.swing.JMenuItem btnEnVenta;
    private javax.swing.JMenuItem btnGestionarCuenta;
    private javax.swing.JMenuItem btnLogOut;
    private javax.swing.JMenu btnMisCompras;
    private javax.swing.JMenuItem btnNoDisponibles;
    private javax.swing.JMenuItem btnProductosComprados;
    private javax.swing.JMenuItem btnRegistroPublicaciones;
    private javax.swing.JMenuItem btnVender;
    private javax.swing.JMenuItem btnVendido;
    private javax.swing.JMenu btnVentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
