/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controladores.ControladorVistaRegistrar;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Pixels
 */
public class vistaRegistrar extends javax.swing.JFrame {
    ControladorVistaRegistrar controlador;

    /**
     * Creates new form registro
     */
    public vistaRegistrar() {
        initComponents();
        this.controlador = new ControladorVistaRegistrar();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboxDia = new javax.swing.JComboBox<>();
        cboxAnio = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        cboxMes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("¡Registra tu cuenta!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Llene la información correctamente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("Nombres*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 118, -1, -1));

        jLabel4.setText("Apellidos*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel5.setText("Usuario*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 60, -1, -1));

        jLabel6.setText("Correo*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 60, -1, -1));

        jLabel7.setText("Documento*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel8.setText("Día*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel9.setText("Telefono*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel10.setText("Mes*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel11.setText("Año*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        cboxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cboxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 55, -1));

        cboxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900    ", "1901    ", "1902    ", "1903    ", "1904    ", "1905    ", "1906    ", "1907    ", "1908    ", "1909", "1910        ", "1911    ", "1912    ", "1913    ", "1914    ", "1915    ", "1916    ", "1917    ", "1918    ", "1919", "1920        ", "1921    ", "1922    ", "1923    ", "1924    ", "1925    ", "1926    ", "1927    ", "1928    ", "1929", "1930    ", "1931    ", "1932    ", "1933    ", "1934    ", "1935    ", "1936    ", "1937    ", "1938    ", "1939", "1940        ", "1941    ", "1942    ", "1943    ", "1944    ", "1945    ", "1946    ", "1947    ", "1948    ", "1949", "1950        ", "1951    ", "1952    ", "1953    ", "1954    ", "1955    ", "1956    ", "1957    ", "1958    ", "1959", "1960        ", "1961    ", "1962    ", "1963    ", "1964    ", "1965    ", "1966    ", "1967    ", "1968    ", "1969", "1970        ", "1971    ", "1972    ", "1973    ", "1974    ", "1975    ", "1976   ", "1977    ", "1978    ", "1979", "1980        ", "1981    ", "1982    ", "1983    ", "1984    ", "1985    ", "1986    ", "1987    ", "1988    ", "1989", "1990    ", "1991    ", "1992    ", "1993    ", "1994    ", "1995    ", "1996    ", "1997    ", "1998    ", "1999", "2000       ", "2001    ", "2002    ", "2003    ", "2004          ", "2005    ", "2006    ", "2007", "2008    ", "2009", "2010       ", "2011    ", "2012    ", "2013    ", "2014    ", "2015   ", "2016", "2017", "2018", "2019", "2020", "2021" }));
        cboxAnio.setSelectedIndex(121);
        cboxAnio.setToolTipText("");
        cboxAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(cboxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 60, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel12.setText("Contraseña*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel13.setText("Confirmar contraseña*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, -1));

        cboxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxMesItemStateChanged(evt);
            }
        });
        jPanel1.add(cboxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 55, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String user = txtUser.getText();
        String correo = txtCorreo.getText();
        String psw = txtPassword.getText();
        String nombre = txtNombres.getText();
        String apellido = txtApellidos.getText();
        String dni = txtDocumento.getText();
        String telefono = txtTelefono.getText();
        if (user.isEmpty() || correo.isEmpty() || psw.isEmpty() || nombre.isEmpty() || apellido.isEmpty()
                || dni.isEmpty() || telefono.isEmpty()) {
            msj("Por favor llene todos los campos");
        } else {
            if (validL(nombre) && validL(apellido) && validN(dni) && validN(telefono)) {
                int dia = Integer.parseInt(cboxDia.getSelectedItem().toString().trim());
                int mes = Integer.parseInt(cboxMes.getSelectedItem().toString().trim());
                int anio = Integer.parseInt(cboxAnio.getSelectedItem().toString().trim());
                Usuario u = new Usuario(user, correo, psw, nombre, apellido, dni, telefono, Usuario.determinarEdad(dia, mes, anio));
                Usuario aux = controlador.buscar(u.getUser());
                boolean aux2 = controlador.validarUsuario(u);
                if (validarPass()) {
                    if (aux == null) {
                        if (aux2) {
                            boolean respuesta = controlador.registrar(u);
                            if (respuesta) {
                                msj("Se registró satisfactoriamente");
                                btnVolver.doClick();
                            } else {
                                msj("No se pudo registrar");
                            }
                        } else {
                            msj("No se pudo registrar, intente cambiar el correo, el documento o el telefono");
                        }
                    } else {
                        msj("No se pudo registrar, el usuario ya existe");
                    }
                } else {
                    msj("Las dos contraseñas ingresadas no coinciden");
                }
            } else {
                msj("Por favor llene los campos con los caracteres correctos");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new vistaLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cboxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxMesItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            cboxDia.setModel(new DefaultComboBoxModel(controlador.obtenerDiasMes(cboxMes.getSelectedItem().toString())));
        }
    }//GEN-LAST:event_cboxMesItemStateChanged

    private boolean validL(String datos){
        return datos.matches("[a-zA-Z]*");
    }
    private boolean validN(String datos){
        return datos.matches("[0-9]*");
    }
    private boolean validarPass(){
        String psw = txtPassword.getText();
        String confrmPsw = txtConfirmPassword.getText();
        return psw.equals(confrmPsw);
    }
    private void msj(String msj){
        JOptionPane.showMessageDialog(this, msj);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboxAnio;
    private javax.swing.JComboBox<String> cboxDia;
    private javax.swing.JComboBox<String> cboxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
