/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaUsuario;
import javax.swing.JOptionPane;
import modelo.Usuario;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelUsuarioModificarCuenta extends javax.swing.JPanel {
    Usuario usuario;
    ControladorVistaUsuario controlador;

    /**
     * Creates new form panelUsuarioGestionarCuenta
     * @param usuario
     */
    public PanelUsuarioModificarCuenta(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.controlador = new ControladorVistaUsuario();
        setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Modifica los datos de tu cuenta!");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Usuario*");
        panelAbsoluto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Correo*");
        panelAbsoluto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Nombres*");
        panelAbsoluto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Apellidos*");
        panelAbsoluto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txtNombres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 30));

        txtApellidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Telefono*");
        panelAbsoluto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Edad*");
        panelAbsoluto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Contraseña*");
        panelAbsoluto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 100, 30));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 120, 90));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        txtEdad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, 30));

        txtConfirmPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 100, 30));

        txtPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelAbsoluto.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Repetir Contraseña*");
        panelAbsoluto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (txtUser.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmPass.getText().isEmpty()
            || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty()
            || txtTelefono.getText().isEmpty() || txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        } else {
            if (validLtrs(txtNombres.getText()) && validLtrs(txtApellidos.getText())
                && validNums(txtTelefono.getText()) && validNums(txtEdad.getText())) {
                String user = txtUser.getText();
                String correo = txtCorreo.getText();
                String psw = txtPass.getText();
                String confirmPsw = txtConfirmPass.getText();
                String nombre = txtNombres.getText();
                String apellido = txtApellidos.getText();
                String telefono = txtTelefono.getText();
                int edad = Integer.parseInt(txtEdad.getText());

                if(!user.equals(usuario.getUser())){
                    Usuario aux = controlador.buscar(user);
                    Usuario aux2 = controlador.buscarAdmin(user);
                    if(aux == null && aux2 == null){
                        usuario.setUser(user);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el usuario, pues este ya está registrado");
                    }
                }
                if(!correo.equals(usuario.getCorreo())){
                    Usuario aux = controlador.buscarCorreo(correo);
                    if(aux == null){
                        usuario.setCorreo(correo);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el correo, pues este ya está registrado");
                    }
                }
                if(!telefono.equals(usuario.getTelefono())){
                    Usuario aux = controlador.buscarTelefono(telefono);
                    if(aux == null){
                        usuario.setTelefono(telefono);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el telefono, pues este ya está registrado");
                    }
                }
                if (psw.equals(confirmPsw)) {
                    usuario.setPsw(psw);
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo modificar la contraseña debido a que no coinciden");
                }
                
                usuario.setNombre(nombre);
                usuario.setApellido(apellido);
                
                if(edad>0 && edad<115){
                    usuario.setEdad(edad);
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo modificar la edad");
                }

                JOptionPane.showMessageDialog(this, "Tus datos han sido modificados correctamente");

                btnVolver.doClick();

            } else {
                JOptionPane.showMessageDialog(this, "Por favor ingrese datos correctos para cada casilla");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        PanelUsuarioInfo p = new PanelUsuarioInfo(usuario);
        p.setSize(635,194);

        panelAbsoluto.removeAll();
        panelAbsoluto.add(p, new AbsoluteConstraints(0,0,-1,-1));
        panelAbsoluto.revalidate();
        panelAbsoluto.repaint();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void setText(){
        txtUser.setText(usuario.getUser());
        txtCorreo.setText(usuario.getCorreo());
        txtPass.setText(usuario.getPsw());
        txtConfirmPass.setText(usuario.getPsw());
        txtNombres.setText(usuario.getNombre());
        txtApellidos.setText(usuario.getApellido());
        txtTelefono.setText(usuario.getTelefono());
        txtEdad.setText(Integer.toString(usuario.getEdad()));
    }
    private boolean validLtrs(String datos){
        return datos.matches("[a-zA-Z]*");
    }
    private boolean validNums(String datos){
        return datos.matches("[0-9]*");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
