/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaAdministrador;
import javax.swing.JOptionPane;
import modelo.Usuario;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelAdminModificarCuenta extends javax.swing.JPanel {
    ControladorVistaAdministrador controlador;
    Usuario admin;

    /**
     * Creates new form panelGestionarCuentaAdministrador
     * @param admin
     */
    public PanelAdminModificarCuenta(Usuario admin) {
        initComponents();
        controlador = new ControladorVistaAdministrador();
        this.admin = admin;
        setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Modificar cuenta!");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("Usuario*");
        panelAbsoluto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Correo*");
        panelAbsoluto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        panelAbsoluto.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel4.setText("Nombres*");
        panelAbsoluto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
        panelAbsoluto.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        jLabel5.setText("Apellidos*");
        panelAbsoluto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
        panelAbsoluto.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, -1));

        jLabel6.setText("Documento*");
        panelAbsoluto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        panelAbsoluto.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, -1));

        jLabel7.setText("Telefono*");
        panelAbsoluto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));
        panelAbsoluto.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, -1));

        jLabel8.setText("Edad*");
        panelAbsoluto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel11.setText("Contraseña*");
        panelAbsoluto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));
        panelAbsoluto.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 80, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 120, 90));
        panelAbsoluto.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, -1));
        panelAbsoluto.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (txtUser.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtPass.getText().isEmpty()
            || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtDocumento.getText().isEmpty()
            || txtTelefono.getText().isEmpty() || txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        } else {
            if (validLtrs(txtNombres.getText()) && validLtrs(txtApellidos.getText())
                && validNums(txtDocumento.getText()) && validNums(txtTelefono.getText()) && validNums(txtEdad.getText())) {
                String user = txtUser.getText();
                String correo = txtCorreo.getText();
                String psw = txtPass.getText();
                String nombre = txtNombres.getText();
                String apellido = txtApellidos.getText();
                String dni = txtDocumento.getText();
                String telefono = txtTelefono.getText();
                int edad = Integer.parseInt(txtEdad.getText());

                admin.setUser(user);
                admin.setCorreo(correo);
                admin.setDni(dni);
                admin.setTelefono(telefono);
                admin.setPsw(psw);
                admin.setNombre(nombre);
                admin.setApellido(apellido);
                admin.setEdad(edad);

                JOptionPane.showMessageDialog(this, "Datos modificados correctamente");
                PanelAdminUsuarios p = new PanelAdminUsuarios();
                p.setSize(635, 194);

                panelAbsoluto.removeAll();
                panelAbsoluto.add(p, new AbsoluteConstraints(0, 0, -1, -1));
                panelAbsoluto.revalidate();
                panelAbsoluto.repaint();

            } else {
                JOptionPane.showMessageDialog(this, "Por favor ingrese datos correctos para cada casilla");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void setText(){
        txtUser.setText(admin.getUser());
        txtCorreo.setText(admin.getCorreo());
        txtPass.setText(admin.getPsw());
        txtNombres.setText(admin.getNombre());
        txtApellidos.setText(admin.getApellido());
        txtDocumento.setText(admin.getDni());
        txtTelefono.setText(admin.getTelefono());
        txtEdad.setText(Integer.toString(admin.getEdad()));
    }
    private boolean validLtrs(String datos){
        return datos.matches("[a-zA-Z]*");
    }
    private boolean validNums(String datos){
        return datos.matches("[0-9]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
