/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaAdministrador;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelAdminUsuarios extends javax.swing.JPanel {
    ControladorVistaAdministrador controlador;

    /**
     * Creates new form panelUsuarios
     */
    public PanelAdminUsuarios() {
        initComponents();
        controlador = new ControladorVistaAdministrador();
        restaurarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        lblUsuariosRegistrados = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnRemoverFiltro = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(635, 194));

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuarios registrados:");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User", "Correo", "Nombre", "Apellido", "Id", "Edad", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuarios);

        panelAbsoluto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 140));

        lblUsuariosRegistrados.setText("0");
        panelAbsoluto.add(lblUsuariosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, -1));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        btnAgregar.setText("Agregar usuario");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        btnRemoverFiltro.setText("Remover filtro");
        btnRemoverFiltro.setEnabled(false);
        btnRemoverFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFiltroActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnRemoverFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        txtFiltro.setText("User, correo, id, tel...");
        txtFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltroMouseClicked(evt);
            }
        });
        panelAbsoluto.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        String filtro = txtFiltro.getText();
        Usuario aux1 = controlador.buscar(filtro);
        Usuario aux2 = controlador.buscarId(filtro);
        Usuario aux3 = controlador.buscarCorreo(filtro);
        Usuario aux4 = controlador.buscarTelefono(filtro);
        
        buscarFiltroTabla(aux1, aux2, aux3, aux4);
        if(aux1 != null || aux2 != null || aux3 != null || aux4 != null){
            activarGestion();
        }else{
            restaurarPanel();
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String filtro = txtFiltro.getText();
        Usuario aux1 = controlador.buscar(filtro);
        Usuario aux2 = controlador.buscarId(filtro);
        Usuario aux3 = controlador.buscarCorreo(filtro);
        Usuario aux4 = controlador.buscarTelefono(filtro);
        
        if(aux1!=null){
            PanelAdminModificarUsuario panel = new PanelAdminModificarUsuario(aux1);
            mostrarPanel(panel);
        } else if (aux2 != null) {
            PanelAdminModificarUsuario panel = new PanelAdminModificarUsuario(aux2);
            mostrarPanel(panel);
        } else if (aux3 != null) {
            PanelAdminModificarUsuario panel = new PanelAdminModificarUsuario(aux3);
            mostrarPanel(panel);
        } else if (aux4 != null) {
            PanelAdminModificarUsuario panel = new PanelAdminModificarUsuario(aux4);
            mostrarPanel(panel);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        PanelAdminAgregar panel = new PanelAdminAgregar();
        mostrarPanel(panel);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRemoverFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFiltroActionPerformed
        // TODO add your handling code here:
        restaurarPanel();
    }//GEN-LAST:event_btnRemoverFiltroActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Está seguro de eliminar el usuario?");
        if (i == 0) {
            String filtro = txtFiltro.getText();
            Usuario auxUser = controlador.buscar(filtro);
            Usuario auxId = controlador.buscarId(filtro);
            Usuario auxCorreo = controlador.buscarCorreo(filtro);
            Usuario auxTelefono = controlador.buscarTelefono(filtro);

            if (auxUser != null) {
                controlador.eliminar(auxUser.getUser());
                restaurarPanel();
            } else if (auxId != null) {
                controlador.eliminar(auxId.getUser());
                restaurarPanel();
            } else if (auxCorreo != null) {
                controlador.eliminar(auxCorreo.getUser());
                restaurarPanel();
            } else if (auxTelefono != null) {
                controlador.eliminar(auxTelefono.getUser());
                restaurarPanel();
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        // TODO add your handling code here:
        int seleccionar = tableUsuarios.rowAtPoint(evt.getPoint());
        String id = tableUsuarios.getValueAt(seleccionar, 0).toString();
        txtFiltro.setText(id);
    }//GEN-LAST:event_tableUsuariosMouseClicked

    private void txtFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltroMouseClicked
        // TODO add your handling code here:
        txtFiltro.setText("");
    }//GEN-LAST:event_txtFiltroMouseClicked

    private void mostrarTabla(){
        crearTabla(controlador.construirMatris());
    }
    private void buscarFiltroTabla(Usuario a, Usuario b, Usuario c, Usuario d) {
        if (a != null) {
            filtrarTabla(a);
        } else if (b != null) {
            filtrarTabla(b);
        } else if (c != null) {
            filtrarTabla(c);
        } else if (d != null) {
            filtrarTabla(d);
        }else if(a == null && b == null && c == null && d == null){
            JOptionPane.showMessageDialog(this, "No se encontró");
        }

    }
    private void filtrarTabla(Usuario u) {
        crearTabla(controlador.contruirMatrisPorUsiario(u));
        
        btnRemoverFiltro.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }
    private void limpiarTxt(){
        txtFiltro.setText("");
    }
    private void mostrarPanel(JPanel p){
        p.setSize(635,194);
        
        panelAbsoluto.removeAll();
        panelAbsoluto.add(p, new AbsoluteConstraints(0,0,-1,-1));
        panelAbsoluto.revalidate();
        panelAbsoluto.repaint();
    }
    private void restaurarPanel(){
        lblUsuariosRegistrados.setText(Integer.toString(controlador.contarUsuarios()));
        mostrarTabla();
        txtFiltro.setVisible(true);
        btnFiltrar.setVisible(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnRemoverFiltro.setEnabled(false);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        btnRemoverFiltro.setVisible(false);
        txtFiltro.setText("User, correo, id, tel...");
    }
    private void activarGestion(){
        txtFiltro.setVisible(false);
        btnFiltrar.setVisible(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnRemoverFiltro.setEnabled(true);
        btnModificar.setVisible(true);
        btnEliminar.setVisible(true);
        btnRemoverFiltro.setVisible(true);
    }
    private void crearTabla(String matris[][]){
        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
                matris,
                new String[]{
                    "User", "Correo", "Nombre", "Apellido", "Id", "Edad", "Telefono"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRemoverFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuariosRegistrados;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
