/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaAdministrador;
import javax.swing.JOptionPane;
import modelo.Producto;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelAdminProductos extends javax.swing.JPanel {
    ControladorVistaAdministrador controlador;
    /**
     * Creates new form panelAdminEnVenta
     */
    public PanelAdminProductos() {
        initComponents();
        controlador = new ControladorVistaAdministrador();
        restaurarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        btnDetalle = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblEnVenta = new javax.swing.JLabel();
        btnRemoverFiltro = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotalProductos = new javax.swing.JLabel();

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableProductos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre", "Descripcion", "Precio", "Stock", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        panelAbsoluto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 130));

        btnDetalle.setText("Ver detalles");
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        btnEliminar.setText("Eliminar producto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        txtFiltro.setText("id...");
        txtFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltroMouseClicked(evt);
            }
        });
        panelAbsoluto.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 90, -1));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Productos en venta:");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblEnVenta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEnVenta.setText("0");
        panelAbsoluto.add(lblEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 40, -1));

        btnRemoverFiltro.setText("Remover");
        btnRemoverFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFiltroActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnRemoverFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        btnModificar.setText("Modificar producto");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Total:");
        panelAbsoluto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lblTotalProductos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTotalProductos.setText("0");
        panelAbsoluto.add(lblTotalProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        // TODO add your handling code here:
        int seleccionar = tableProductos.rowAtPoint(evt.getPoint());
        String idProducto = tableProductos.getValueAt(seleccionar, 0).toString();
        txtFiltro.setText(idProducto);
    }//GEN-LAST:event_tableProductosMouseClicked

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        Producto aux = controlador.buscarProducto(txtFiltro.getText());
        if(aux!=null){
            filtrarTabla();
            txtFiltro.setEnabled(false);
            btnFiltrar.setVisible(false);
            btnRemoverFiltro.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltroMouseClicked
        // TODO add your handling code here:
        txtFiltro.setText("");
    }//GEN-LAST:event_txtFiltroMouseClicked

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        // TODO add your handling code here:
        Producto aux = controlador.buscarProducto(txtFiltro.getText());
        if(aux!=null){
            String disponibilidad = "NO";
            if(aux.isDisponible()){
                disponibilidad = "SI";
            }
            JOptionPane.showMessageDialog(this, "Id: "+ aux.getId() + "\nNombre: " + aux.getNombre()
            +"\nDescripcion: "+aux.getDesc() + "\nPrecio: $"+aux.getPrecio() + "\nCategoría: "+aux.getCategoria().getNombre()
            +"\nStock: "+aux.getStock()+"\nDisponible: "+disponibilidad + "\nDueño: " + aux.getUsuario().getUser()
            +"\nFecha publicación: "+aux.getFechaPublicacion());
        }else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
        }
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void btnRemoverFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFiltroActionPerformed
        // TODO add your handling code here:
        restaurarPanel();
    }//GEN-LAST:event_btnRemoverFiltroActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String id = txtFiltro.getText();
        Producto aux = controlador.buscarProducto(id);
        if(aux!=null){
            int i = JOptionPane.showConfirmDialog(this, "Está seguro de quitar el producto a la venta?");
            if(i == 0){
                boolean respuesta = controlador.eliminarProducto(aux.getId());
                restaurarPanel();
                if(respuesta){
                    JOptionPane.showMessageDialog(this, "Producto eliminado completamente");
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Id de producto no encontrada");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String id = txtFiltro.getText();
        Producto aux = controlador.buscarProducto(id);
        
        if(aux != null){
            PanelAdminModificarProducto panel = new PanelAdminModificarProducto(aux);
            panel.setSize(635, 194);
            
            panelAbsoluto.removeAll();
            panelAbsoluto.add(panel, new AbsoluteConstraints(0, 0, -1, -1));
            panelAbsoluto.revalidate();
            panelAbsoluto.repaint();
        }else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void mostrarTabla(){
        crearTabla(controlador.construirMatrisProductosEnVenta());
    }
    private void filtrarTabla(){
        crearTabla(controlador.contruirMatrisFiltroProducto(txtFiltro.getText()));
    }
    private void crearTabla(String mtrx[][]){
        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            mtrx,
            new String [] {
                "Id Producto", "Nombre", "Descripcion", "Precio", "Stock", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private void restaurarPanel(){
        lblEnVenta.setText(Integer.toString(controlador.obtenerProductosEnVenta()));
        lblTotalProductos.setText(Integer.toString(controlador.obtenerTotalProductos()));
        mostrarTabla();
        txtFiltro.setEnabled(true);
        btnFiltrar.setVisible(true);
        btnRemoverFiltro.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRemoverFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnVenta;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
