/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaUsuarioCompra;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.Venta;

/**
 *
 * @author Pixels
 */
public class PanelUsuarioDineroGastado extends javax.swing.JPanel {
    ControladorVistaUsuarioCompra controlador;
    Usuario usuario;

    /**
     * Creates new form PanelUsuarioDinero
     * @param usuario
     */
    public PanelUsuarioDineroGastado(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        controlador = new ControladorVistaUsuarioCompra();
        lblDinero.setText(Double.toString(controlador.dineroTotalGastadoUsuario(usuario.getUser())));
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDinero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDinero = new javax.swing.JTable();
        btnInfo = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Dinero total gastado: $");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblDinero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDinero.setText("0");
        jPanel1.add(lblDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, -1));

        tableDinero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Dinero gastado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDineroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDinero);
        if (tableDinero.getColumnModel().getColumnCount() > 0) {
            tableDinero.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableDinero.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 490, 240));

        btnInfo.setText("Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 90, 30));

        txtFiltro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFiltro.setText("Id de compra...");
        txtFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltroMouseClicked(evt);
            }
        });
        jPanel1.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltroMouseClicked
        // TODO add your handling code here:
        txtFiltro.setText("");
    }//GEN-LAST:event_txtFiltroMouseClicked

    private void tableDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDineroMouseClicked
        // TODO add your handling code here:
        int fila = tableDinero.rowAtPoint(evt.getPoint());
        String idCompra = tableDinero.getValueAt(fila, 0).toString();
        txtFiltro.setText(idCompra);
    }//GEN-LAST:event_tableDineroMouseClicked

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        Venta aux = controlador.buscarVenta(txtFiltro.getText());
        if(aux!=null && aux.getComprador().getUser().equals(usuario.getUser())){
            JOptionPane.showMessageDialog(this, "Gasto total: "+aux.getPrecioTotal() + "\nPrecio por unidad: "+aux.getProducto().getPrecio()+
                    "\nUnidades compradas: "+aux.getProducto().getCantidad() + "\n\nVendedor: "+aux.getVendedor().getUser());
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró la compra con el id ingresado");
        }
    }//GEN-LAST:event_btnInfoActionPerformed

    private void mostrarTabla(){
        tableDinero.setModel(new javax.swing.table.DefaultTableModel(
            controlador.construirMatrisDineroGastadoUsuario(usuario.getUser()),
            new String [] {
                "Id", "Nombre", "Dinero gastado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JTable tableDinero;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
