/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaAdministrador;
import javax.swing.JOptionPane;
import modelo.Categoria;

/**
 *
 * @author Pixels
 */
public class PanelAdminCategorias extends javax.swing.JPanel {
    ControladorVistaAdministrador controlador;
    private String nombreCategoria;

    /**
     * Creates new form PanelAdminCategorias
     */
    public PanelAdminCategorias() {
        initComponents();
        controlador = new ControladorVistaAdministrador();
        restaurarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();
        btnAgregarCategoria = new javax.swing.JButton();
        btnEliminarCategoria = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Total categorías:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblCategorias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCategorias.setText("0");
        jPanel1.add(lblCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, -1));

        tableCategorias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategorias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 420, 140));

        btnAgregarCategoria.setText("Agregar categoría");
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 150, 40));

        btnEliminarCategoria.setText("Eliminar");
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 104, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre de la nueva categoría");
        if (nombre != null && !nombre.isEmpty() && validLtrs(nombre)) {
            boolean respuesta = controlador.agregarCategoria(new Categoria(nombre));
            if (respuesta) {
                JOptionPane.showMessageDialog(this, "Categoría agregada");
                restaurarPanel();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar, ya existe una categoría con el nombre ingresado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor ingrese caracteres correctos");
        }
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        // TODO add your handling code here:
        Categoria aux = controlador.buscarCategoria(nombreCategoria);
        if(aux != null){
            int i = JOptionPane.showConfirmDialog(this, "Está seguro de eliminar la categoría "+aux.getNombre().toUpperCase()+"?");
            if(i == 0){
                boolean respuesta = controlador.eliminarCategoria(aux.getNombre());
                if(respuesta){
                    restaurarPanel();
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione una categoría");
        }
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    private void tableCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriasMouseClicked
        // TODO add your handling code here:
        int fila = tableCategorias.rowAtPoint(evt.getPoint());
        nombreCategoria = tableCategorias.getValueAt(fila, 0).toString();
    }//GEN-LAST:event_tableCategoriasMouseClicked

    private void mostrarTabla(){
        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            controlador.matrisCategorias(),
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private void restaurarPanel(){
        mostrarTabla();
        lblCategorias.setText(Integer.toString(controlador.obtenerCategorias().length));
    }
    private boolean validLtrs(String datos){
        return datos.matches("[a-zA-Z´]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JTable tableCategorias;
    // End of variables declaration//GEN-END:variables
}
