/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaAdministrador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Producto;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelAdminModificarProducto extends javax.swing.JPanel {
    ControladorVistaAdministrador controlador;
    Producto producto;

    /**
     * Creates new form panelAdminModificarProducto
     * @param producto
     */
    public PanelAdminModificarProducto(Producto producto) {
        initComponents();
        controlador = new ControladorVistaAdministrador();
        this.producto = producto;
        llenarBoxCategorias();
        llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cboxEstado = new javax.swing.JComboBox<>();
        cboxCategoria = new javax.swing.JComboBox<>();

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Modificar producto");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        panelAbsoluto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Precio:");
        panelAbsoluto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion:");
        panelAbsoluto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Categoria:");
        panelAbsoluto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Stock:");
        panelAbsoluto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Estado:");
        panelAbsoluto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 190, 30));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));
        panelAbsoluto.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 100, -1));
        panelAbsoluto.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));
        panelAbsoluto.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));
        panelAbsoluto.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));

        cboxEstado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));
        panelAbsoluto.add(cboxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 140, 30));

        cboxCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cboxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Electrodomesticos" }));
        panelAbsoluto.add(cboxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty() || txtPrecio.getText().isEmpty() || txtDescripcion.getText().isEmpty()
            || txtStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        }else{
            if(validNums(txtPrecio.getText()) && validNums(txtStock.getText())){
                String nombre = txtNombre.getText();
                double precio = Double.parseDouble(txtPrecio.getText());
                String descripcion = txtDescripcion.getText();
                int stock = Integer.parseInt(txtStock.getText());
                Categoria categoria = new Categoria(cboxCategoria.getSelectedItem().toString());
                String estado = cboxEstado.getSelectedItem().toString();
                
                producto.setNombre(nombre);
                producto.setPrecio(precio);
                producto.setDesc(descripcion);
                producto.setCategoria(categoria);
                
                if(estado.equals("Disponible")){
                    producto.setDisponible(true);
                }else{
                    producto.setDisponible(false);
                    JOptionPane.showMessageDialog(this, "Producto retirado de la venta por estado NO disponible");
                }
                if (stock >= 0) {
                    producto.setStock(stock);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo modificar el stock, ya que debe ser mayor o igual a 0");
                }
                if (stock == 0) {
                    producto.setDisponible(false);
                    JOptionPane.showMessageDialog(this, "Producto retirado de la venta debido a que no tiene unidades disponibles");
                }
                
                btnVolver.doClick();
                
            }else{
                JOptionPane.showMessageDialog(this, "Por favor llene los campos con caracteres correctos");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        PanelAdminProductos panel = new PanelAdminProductos();
        panel.setSize(635, 194);

        panelAbsoluto.removeAll();
        panelAbsoluto.add(panel, new AbsoluteConstraints(0, 0, -1, -1));
        panelAbsoluto.revalidate();
        panelAbsoluto.repaint();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void llenarCampos(){
        txtNombre.setText(producto.getNombre());
        txtPrecio.setText(Double.toString(producto.getPrecio()));
        txtDescripcion.setText(producto.getDesc());
        txtStock.setText(Integer.toString(producto.getStock()));
        cboxCategoria.setSelectedItem(producto.getCategoria().getNombre());
        if(producto.isDisponible()){
            cboxEstado.setSelectedIndex(0);
        }else{
            cboxEstado.setSelectedIndex(1);
        }
    }
    private void llenarBoxCategorias(){
        cboxCategoria.setModel(new DefaultComboBoxModel(controlador.obtenerCategorias()));
    }
    private boolean validNums(String datos){
        return datos.matches("[0-9.]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboxCategoria;
    private javax.swing.JComboBox<String> cboxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
