/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaUsuarioVenta;
import javax.swing.JOptionPane;
import modelo.Producto;
import modelo.Usuario;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelUsuarioEnVenta extends javax.swing.JPanel {
    Usuario usuario;
    ControladorVistaUsuarioVenta controlador;

    /**
     * Creates new form panelUsuarioVentas
     * @param usuario
     */
    public PanelUsuarioEnVenta(Usuario usuario) {
        initComponents();
        this.controlador = new ControladorVistaUsuarioVenta();
        this.usuario = usuario;
        lblProductosEnVenta.setText(Integer.toString(controlador.obtenerProductosVentaUsuario(usuario.getUser())));
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProductosEnVenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        btnInformacion = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Productos en venta:");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblProductosEnVenta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblProductosEnVenta.setText("0");
        panelAbsoluto.add(lblProductosEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 50, -1));

        tableProductos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        panelAbsoluto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 250));

        btnInformacion.setText("Informacion completa");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        btnModificar.setText("Modificar producto");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        btnEliminar.setText("Dejar de vender");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        txtFiltro.setText("Id...");
        txtFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltroMouseClicked(evt);
            }
        });
        panelAbsoluto.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        // TODO add your handling code here:
        int seleccionar = tableProductos.rowAtPoint(evt.getPoint());
        String idProducto = tableProductos.getValueAt(seleccionar, 0).toString();
        txtFiltro.setText(idProducto);
    }//GEN-LAST:event_tableProductosMouseClicked

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
        String id = txtFiltro.getText();
        Producto aux = controlador.buscar(id);
        if(aux!=null && aux.getUsuario().getUser().equals(usuario.getUser())){
            String disponibilidad = "NO";
            if(aux.isDisponible()){
                disponibilidad = "SI";
            }
            JOptionPane.showMessageDialog(this, "Id: "+ aux.getId() + "\nNombre: " + aux.getNombre()
            +"\nDescripcion: "+aux.getDesc() + "\nPrecio: $"+aux.getPrecio() + "\nCategoría: "+aux.getCategoria().getNombre()
            +"\nStock: "+aux.getStock()+"\nDisponible: "+disponibilidad + "\nDueño: " + aux.getUsuario().getUser()
            +"\nFecha publicación: "+aux.getFechaPublicacion());
        }else{
            JOptionPane.showMessageDialog(this, "Id de producto no encontrada");
        }
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void txtFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltroMouseClicked
        // TODO add your handling code here:
        txtFiltro.setText("");
    }//GEN-LAST:event_txtFiltroMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String id = txtFiltro.getText();
        Producto aux = controlador.buscar(id);
        if(aux!=null && aux.getUsuario().getUser().equals(usuario.getUser())){
            PanelUsuarioModificarProducto panel = new PanelUsuarioModificarProducto(aux);
            panel.setSize(700, 310);
            
            panelAbsoluto.removeAll();
            panelAbsoluto.add(panel, new AbsoluteConstraints(0, 0, -1, -1));
            panelAbsoluto.revalidate();
            panelAbsoluto.repaint();
        }else{
            JOptionPane.showMessageDialog(this, "Id de producto no encontrada");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String id = txtFiltro.getText();
        Producto aux = controlador.buscar(id);
        if(aux!=null && aux.getUsuario().getUser().equals(usuario.getUser())){
            int i = JOptionPane.showConfirmDialog(this, "Está seguro de quitar el producto a la venta?");
            if(i == 0){
                controlador.eliminar(aux.getId());
                lblProductosEnVenta.setText(Integer.toString(controlador.obtenerProductosVentaUsuario(usuario.getUser())));
                mostrarTabla();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Id de producto no encontrada");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    private void mostrarTabla(){
        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            controlador.construirMatrisProductosEnVentaUsuario(usuario),
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductosEnVenta;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
