/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControladorVistaAdministrador;
import javax.swing.JOptionPane;
import modelo.Usuario;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Pixels
 */
public class PanelAdminModificarUsuario extends javax.swing.JPanel {
    ControladorVistaAdministrador controlador;
    Usuario usuario;

    /**
     * Creates new form panelAdminModificar
     * @param usuario
     */
    public PanelAdminModificarUsuario(Usuario usuario) {
        initComponents();
        controlador = new ControladorVistaAdministrador();
        this.usuario = usuario;
        setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAbsoluto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();

        panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Modificar usuarios!");
        panelAbsoluto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("Usuario*");
        panelAbsoluto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Correo*");
        panelAbsoluto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        panelAbsoluto.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel4.setText("Nombres*");
        panelAbsoluto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
        panelAbsoluto.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        jLabel5.setText("Apellidos*");
        panelAbsoluto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        panelAbsoluto.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, -1));

        jLabel6.setText("Documento*");
        panelAbsoluto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
        panelAbsoluto.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, -1));

        jLabel7.setText("Telefono*");
        panelAbsoluto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));
        panelAbsoluto.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, -1));

        jLabel8.setText("Edad*");
        panelAbsoluto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel11.setText("Contraseña*");
        panelAbsoluto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));
        panelAbsoluto.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 80, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, 90));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelAbsoluto.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));
        panelAbsoluto.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, -1));
        panelAbsoluto.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluto, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (txtUser.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtPass.getText().isEmpty()
                || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtDocumento.getText().isEmpty()
                || txtTelefono.getText().isEmpty() || txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        } else {
            if (validLtrs(txtNombres.getText()) && validLtrs(txtApellidos.getText())
                    && validNums(txtDocumento.getText()) && validNums(txtTelefono.getText()) && validNums(txtEdad.getText())) {
                String user = txtUser.getText();
                String correo = txtCorreo.getText();
                String psw = txtPass.getText();
                String nombre = txtNombres.getText();
                String apellido = txtApellidos.getText();
                String dni = txtDocumento.getText();
                String telefono = txtTelefono.getText();
                int edad = Integer.parseInt(txtEdad.getText());
                
                if(!user.equals(usuario.getUser())){
                    Usuario aux = controlador.buscar(user);
                    Usuario aux2 = controlador.buscarAdmin(user);
                    if(aux == null && aux2 == null){
                        usuario.setUser(user);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el usuario, pues este ya está registrado");
                    }
                }
                if(!correo.equals(usuario.getCorreo())){
                    Usuario aux = controlador.buscarCorreo(correo);
                    if(aux == null){
                        usuario.setCorreo(correo);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el correo, pues este ya está registrado");
                    }
                }
                if(!dni.equals(usuario.getDni())){
                    Usuario aux = controlador.buscarId(dni);
                    if(aux == null){
                        usuario.setDni(dni);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el documento, pues este ya está registrado");
                    }
                }
                if(!telefono.equals(usuario.getTelefono())){
                    Usuario aux = controlador.buscarTelefono(telefono);
                    if(aux == null){
                        usuario.setTelefono(telefono);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo modificar el telefono, pues este ya está registrado");
                    }
                }
                
                usuario.setPsw(psw);
                usuario.setNombre(nombre);
                usuario.setApellido(apellido);
                usuario.setEdad(edad);

                JOptionPane.showMessageDialog(this, "El usuario ha sido modificado");

                btnVolver.doClick();

            } else {
                JOptionPane.showMessageDialog(this, "Por favor ingrese datos correctos para cada casilla");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        PanelAdminUsuarios p = new PanelAdminUsuarios();
        p.setSize(635,194);

        panelAbsoluto.removeAll();
        panelAbsoluto.add(p, new AbsoluteConstraints(0,0,-1,-1));
        panelAbsoluto.revalidate();
        panelAbsoluto.repaint();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void setText(){
        txtUser.setText(usuario.getUser());
        txtCorreo.setText(usuario.getCorreo());
        txtPass.setText(usuario.getPsw());
        txtNombres.setText(usuario.getNombre());
        txtApellidos.setText(usuario.getApellido());
        txtDocumento.setText(usuario.getDni());
        txtTelefono.setText(usuario.getTelefono());
        txtEdad.setText(Integer.toString(usuario.getEdad()));
    }
    private boolean validLtrs(String datos){
        return datos.matches("[a-zA-Z]*");
    }
    private boolean validNums(String datos){
        return datos.matches("[0-9]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelAbsoluto;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
